---
- name: Install required packages
  apt:
    name:
      - python3-pip
      - python3-venv
      - git
    state: present
  become: true

- name: Create deployment directory
  file:
    path: "{{ deploy_folder }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create instance directory
  file:
    path: "{{ instance_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy configuration files to instance directory
  template:
    src: config.py.j2
    dest: "{{ instance_path }}/config.py"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Template run.sh script
  template:
    src: run.sh.j2
    dest: "{{ deploy_folder }}/run.sh"
    owner: www-data
    group: www-data
    mode: '0755'

- name: Create virtual environment
  command: python3 -m venv venv
  args:
    chdir: "{{ deploy_folder }}"

- name: Install the Python application wheel
  pip:
    name: "{{ deploy_folder }}/files/{{ wheel_file }}"
    virtualenv: "{{ deploy_folder }}/venv"

- name: Deploy the application wheel
  pip:
    name: "{{ deploy_folder }}/files/{{ wheel_file }}"
    virtualenv: "{{ deploy_folder }}/venv"

- name: Deploy the systemd service file
  template:
    src: example.service.j2
    dest: /etc/systemd/system/example.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and start example service
  systemd:
    name: example.service
    state: started
    enabled: true

